phpunit now namespaced
zendframework/tutorials pull request #104
Opened 2018-12-14 21:16 UTC by onamission

After updating phpunit to version 6 or greater released on 2017-02-03 (e.g. with composer), phpunit code is now namespaced.  Hence the lines
    use PHPUnit_Framework_TestCase as TestCase;
needs to be changed to 
    use PHPUnit\Framework\TestCase as TestCase;

2018-12-14 21:17 UTC, Ocramius requested changes

2018-12-14 21:17 UTC, Ocramius commented on doc/book/unit-testing.md
> +use PHPUnit\Framework\TestCase as TestCase;
`as TestCase` is redundant

2018-12-14 21:17 UTC, Ocramius commented on doc/book/unit-testing.md
> +use PHPUnit\Framework\TestCase as TestCase;
`as TestCase` is redundant

2018-12-17 10:29 UTC, malukenho approved these changes

2018-12-17 21:48 UTC, merged