error in line 39
zendframework/tutorials pull request #60
Opened 2016-09-27 23:46 UTC by stefanocosaro

the command:
$db = new PDO('sqlite:' . realpath(__DIR__) . 'zftutorial.db');
it should be
$db = new PDO('sqlite:' . realpath(__DIR__) . '/zftutorial.db');
otherwise it does not work.
creates a  file datazftutorial.db in the root of the project.

2016-10-01 18:47 UTC, adamlundrigan commented on doc/book/in-depth-guide/zend-db-sql-zend-hydrator.md
> +$db = new PDO('sqlite:' . realpath(__DIR__) . '/zftutorial.db');
Off-topic I know, but `realpath` call is redundant here.  Otherwise, :+1:

2017-03-06 16:39 UTC, froschdesign requested changes

2017-03-06 16:39 UTC, froschdesign commented on doc/book/in-depth-guide/zend-db-sql-zend-hydrator.md
> +$db = new PDO('sqlite:' . realpath(__DIR__) . '/zftutorial.db');
@stefanocosaro 
Please remove `realpath`. Thanks!

2017-05-24 06:30 UTC, merged

2017-05-24 06:31 UTC, froschdesign commented
@stefanocosaro 
Thanks!